import CenterVertically from '@/components/CenterVertically'
import Section from '@/components/Section'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Joakim Tveter – Webutvikler</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='' />
				<link
					href='https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap'
					rel='stylesheet'
				/>
			</Head>
			<Section fullHeigt={true}>
				<CenterVertically>
					<h1>Hei mitt navn er Joakim Tveter</h1>
					<p className='h4'>
						Jeg måtte bytte ut siden min i en fart, så den nye er ikke helt ferdig enda.
					</p>
					<a href='https://www.linkedin.com/in/joakim-tveter/'>Kontakt meg på LinkedIn</a>
				</CenterVertically>
			</Section>
		</>
	)
}
